# This configuration file tells GraphQL Code Generator how
# to generate types based on the schema.
# see https://www.apollographql.com/docs/apollo-server/workflow/generate-types

schema: "../schema.graphql"
generates:
  src/types/resolvers-types.d.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
